### PR TITLE
Fix license badge issues

### PR DESCRIPTION
**Pull request by Raindeer44**
Like you mentioned in issue #11, the license badge image wouldn't load consistently. For me, it was just a regular link about 75% of the time. I put both badges on the same line with just a space in between and it appears to have fixed the issue for me.

### CODE REVIEW

**Comment by spences10** [comment]
Hey @Raindeer44 thanks for your contribution

So, looking at the file:
image

This is showing the badges on the same row, is that right?

**Comment by Raindeer44** [comment]
That's correct; were you trying to put them on separate rows?

**Comment by spences10** [comment]
No, I'm just confused. I thought it would have gone into another row.

**Comment by Raindeer44** [comment]
To get it into another row in markdown, there would need to be two newlines in between them (unless there's some wizardry I don't know about, which is very possible). However, I think it looks better as one row.

**Comment by spences10** [comment]
@Raindeer44 no, I think it looks better on one row too, thanks for this 👍

**Comment by Raindeer44** [comment]
No problem! :smiley:

**Pull request merged**
